// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	entity "github.com/fabianoshz/tg-runner/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// CalculateDependenciesInterface is an autogenerated mock type for the CalculateDependenciesInterface type
type CalculateDependenciesInterface struct {
	mock.Mock
}

// CalculateDependencies provides a mock function with given fields: _a0
func (_m *CalculateDependenciesInterface) CalculateDependencies(_a0 []entity.Resource) [][]entity.Resource {
	ret := _m.Called(_a0)

	var r0 [][]entity.Resource
	if rf, ok := ret.Get(0).(func([]entity.Resource) [][]entity.Resource); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([][]entity.Resource)
		}
	}

	return r0
}

type mockConstructorTestingTNewCalculateDependenciesInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewCalculateDependenciesInterface creates a new instance of CalculateDependenciesInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCalculateDependenciesInterface(t mockConstructorTestingTNewCalculateDependenciesInterface) *CalculateDependenciesInterface {
	mock := &CalculateDependenciesInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
